#!/bin/bash
#bclient <machine> <port> <file> <N-threads> <N-cycles>

#Indicates the name or IP address where the server is running
MACHINE=$1

#The port number of the corresponding server
PORT=$2

#The path to the file that is going to be transferred 
#(it could be a text file or an image of any size)
FILE=$3

#Number of threads that are to be created to send requests to the corresponding server. 
THREADS=$4

#Number of cycles that each thread is going to repeat the request.
CYCLES=$5

#Report CSV format that summarize:
#Test;Requests;Initial request time;Kind of file;Size of file;Response time;Amount of requests;Average response time

#compiles the c file that is going measure the times
gcc -pthread benchmark.c

#execute the script
sudo ./a.out $MACHINE $PORT $FILE $THREADS $CYCLES




